# #Question2
# """Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1,2,3,5,8,13...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms"""

def fibonacci():
    i = 1
    arr = [1,2]
    realarr = []
    while arr[i] < 4000000 :
        arr.append(arr[i]+arr[i-1])
        i+=1
    arr.pop()#Because of arr[i] > 4000000
    for i in arr:
        if i%2 ==0:
            realarr.append(i)

    return sum(realarr)

""" Check:
a = fibonacci()
print(a)"""